### ISSUE TITLE
Nerdfont Bug

### ISSUE THREAD

**Issue by SevenChords** [ttytm/wthrr-the-weathercrab#133]
![image](https://user-images.githubusercontent.com/31819497/236032041-08f7f6ce-89cb-48e4-8071-5557f5d0ad61.png)
This doesn't look right.....
using the Firacode Mono Nerd Font i found on the nerd font page you linked in the install.md

**Comment by kevinmatthes** [comment]
I have the same (or a similar) problem with Nerd Fonts' Hack.  On my machine, it looks even weirder.  I get Asian characters instead of the weather symbols and tofu for the greeting emojis.

**Comment by tobealive** [comment]
Hey @SevenChords,

Can you give further inside about the os you are using? From the crab emoji, my first guess would be you are using mac but just to be sure.

Trying to give some first aid: The line characters in the graph are **not** provided by nerd fonts. Your terminal draws them from a unicode symbol font that needs to be installed as well. It's also listed in the in the install.md.
To give an alternative without installing anything: the necessary characters for another graph style setting might already be available on your system.

**Comment by ttytm** [comment]
On all platforms tested this came down to missing fonts. I think the best solution is that I provide better installation and dependency instructions.

[INSTALL.md](https://github.com/ttytm/wthrr-the-weathercrab/blob/main/INSTALL.md) was extended.

Please reach out again if there are further problems.
