### ISSUE TITLE
support for other fonts

### ISSUE THREAD

**Issue by exo-cortex** [ttytm/wthrr-the-weathercrab#176]
When using fonts other than the `JetBrainsMono Nerd`-font mentioned in the README.md there are some rendering-errors visible e.g. the weather-symbols (sunny, cloudy, etc) are not rendered. I use the font `Plex mono` (the ibm-font) which I would rather keep. 
maybe some `compatibility-mode` might be a nice workaround.

**Comment by tobealive** [comment]
Hi @exo-cortex,

sorry for taking long 🫣 and for the inconvenience.
The font icons that come from nerd fonts are usually not bound to a single nerd font. Every font that is patched to include nerd icons can work - provided that a version of the nerdfont is installed that includes the.

So please make sure that you have installed the latest version of the nerd font. A save way is to get them directly from the nerd-fonts repository.

Some unicode icons / emoji do not come from nerdfonts tho, you need to have an emoji font on your system installed. I might can help you further if you post a screenshot of what icons are missing and give info about what system you are using.

I'll workout a fallback in the mid-term, currently there is very little time to work on the project :/

**Comment by ttytm** [comment]
I tried to clarify this in the updated installation instructions. I'll close the issue for now. Let me know if there you encounter other problems.
