### ISSUE TITLE
FR: configure which characters to use as "icons" for weather

### ISSUE THREAD

**Issue by nkh** [ttytm/wthrr-the-weathercrab#241]
Not all fonts have the characters you are using, I get squares and arrows.

**Comment by ttytm** [comment]
Hey @nkh,

Yes, it's true that not all fonts support the used characters.

It was tried to mention at several places that a dependency to use wthrr are fonts the that add support for the characters.
E.g.
- https://github.com/ttytm/wthrr-the-weathercrab#installation
- https://github.com/ttytm/wthrr-the-weathercrab/blob/main/INSTALL.md#requirements

Most terminal fonts have patched "nerd variants", for this please refer to the install instructions above.

A PR that makes icons configurable or adds fallbacks if the installation instructions were not followed is welcome, but I do not plan to work on it from my end.
