### ISSUE TITLE
Provide a .deb package

### ISSUE THREAD

**Issue by sbstn87** [ttytm/wthrr-the-weathercrab#309]
Hi,

will it be possible to provide a .deb package with the releases?

**Comment by ttytm** [comment]
Looking into it already.

**Comment by ttytm** [comment]
The upcoming release will include the .deb format.

The linux artifact thats part of the workflow runs includes them already
https://github.com/ttytm/wthrr-the-weathercrab/actions/runs/9481485633?pr=329
