### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by BjoernGoettler** [ttytm/wthrr-the-weathercrab#355]
There is a small typo in the documentation regarding configurations.
The example of the time-format in wthrr.ron says `ap_pm` and it throws an error because it expects `am_pm`

**Comment by ttytm** [comment]
Good observation @BjoernGoettler, thank you!

If you like to, you can submit the fix as a PR. Let me know what you prefer 🙂

**Comment by BjoernGoettler** [comment]
I would love to do it...and I actually already tried, but couldn't push my branch.
I'll go through your writtings again, and see if I missed something
